# -*- coding: utf-8 -*-
"""Jogo_da_Forca.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxS2NX4iGJlYgM0ch_4FGEfhFrSkpW5o
"""

"""
Jogo da Forca 
Autor: Guilherme Gustavo e Carla
Funcao: Jogar o jogo da forca com o usuário
"""

#Importando o módulo RANDOM - para escolha aleatório de palavra-secreta
import random

#Criando uma lista vazia para armazenar informações
lista = []
letras_escolhidas = []
tentativas = 0
vidas = 6


#Início do Jogo 
print("***JOGO DA FORCA***\n")

#Pedindo para o usuário digitar a quantidade de palavras que ele deseja para que seja armazenado dentro de uma lista
quantidade = int(input("Digite a quantidade de palavras que deseja armazenar no jogo: ")) 
for i in range(0, quantidade): #para cada interação iniciando do zero ate 1 a menos que a qntd digitada pelo usuário
    escolher = input("Digite uma palavra: ") #escolher é o nome da variavel que dei para as palavras que o usuário digitara para ser a palavra da forca
    lista.append(escolher) #adicionar a palavra escolhida pelo usuário (denominada: escolher) na lista chamada lista
    palavra_escolhida = random.choice(lista).upper() #o módulo random.choice ira selecionar uma palavra dentro da lista de palavras armazenadas e a chamará de 'palavra_escolhida'
     
#Mostrando ao usuário a qntd de letras que a palavra escolhida pelo módulo random possui
print('\nA palavra escolhida contem ', len(palavra_escolhida), 'caracteres',"_ " * len(palavra_escolhida))

estado_atual = ["_"] * len(palavra_escolhida)

while tentativas < vidas: #enquanto a qntd de tentativas for menor que a qntd de vidas, executar o bloco de código abaixo
    letra = str(input("\nDigite uma letra: ")).upper() #pedindo ao usuário uma letra
    letras_escolhidas.append(letra)
    if letra in palavra_escolhida:
        print ("Parabéns, você acertou a letra!")
        for i in range(len(palavra_escolhida)):
            if letra == palavra_escolhida[i]:
                estado_atual[i] = letra
    else:
        print ("Que pena, você errou!")
        tentativas = tentativas + 1


    if tentativas == 0:
        print()
        print("|----- ")
        print("|    | ")
        print("|      ")
        print("|      ")
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif tentativas == 1:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|      ")
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif tentativas == 2:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    | ")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif tentativas == 3:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    |\\ ")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif tentativas == 4:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif tentativas == 5:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|     \\ ")
        print("_      ")
        print()
    elif tentativas == 6:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|   / \\ ")
        print("_      ")
        print()
	# quantas tentativas ele tem
    print ("\nVocê já fez", tentativas, "tentativas erradas e ainda tem", vidas-tentativas, "tentativas\n" )

	# qual o estado atual da palavra
    print ("PALAVRA:", estado_atual)

	# Mostrando ao usuário quais as letras que ele já tentou
    print ("\nLETRAS JA ESCOLHIDAS: ")
    for item in letras_escolhidas:
        print (item, end=" ")  

# Final do jogo
if tentativas == vidas:
	print ("\nAcabaram suas tentativas e VOCÊ PERDEU!!!\n", "A palavra era", palavra_escolhida)
else:
	print ("\n\nPARABÉNS!!! Você venceu...")